name: Release

on:
  push:
    tags:
      - v1.*

jobs:
  build:
    uses: silx-kit/jupyterlab-h5web/.github/workflows/build.yml@main
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'

      - name: Download the built extension
        uses: actions/download-artifact@v2
        with:
          name: jupyterlab_h5web-dist
          path: dist

      - name: Publish package on PyPI 🎉
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pip install -U twine
          twine upload dist/*
